# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12J_ThDJDL1Lzs1p9d3bFKeoEticmhk7q
"""

# =============================================================================
# AI Data Insights Analyst — Analyst in a Box
# Use Case 5 — AI Hackathon Lucknow Feb 21' 2026
#
# Upload any CSV → data cleaning, summary stats, trend analysis, outlier
# detection, auto-charts (agent-decided), business insights → full PDF in ~10s.
# =============================================================================

# # --- Cell 1: Install dependencies (run once) ---
# !pip install -q pandas numpy polars scikit-learn scipy statsmodels reportlab openai httpx python-dotenv tqdm matplotlib seaborn

# --- Cell 2: Imports ---
import os
import time
import json
import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest
from scipy import stats
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from tqdm import tqdm

# --- Cell 3: Data Understanding + Cleaning ---
class DataUnderstandingAgent:
    """Load CSV and return cleaned DataFrame with metadata."""

    def load_data(self, file_path: str):
        size_mb = os.path.getsize(file_path) / (1024 * 1024)
        print(f"Dataset Size: {size_mb:.2f} MB")
        df = pd.read_csv(file_path)
        df, clean_info = self.clean_data(df)
        return df, clean_info

    def clean_data(self, df: pd.DataFrame):
        """Data cleaning: drop empty rows/cols, fill missing, infer types, dedupe."""
        info = {"rows_before": len(df), "cols_before": len(df.columns)}
        # Drop fully empty rows/columns
        df = df.dropna(how="all").dropna(axis=1, how="all")
        # Fill numeric missing with median, categorical with mode
        for c in df.columns:
            if df[c].dtype in [np.number, "float64", "int64"]:
                df[c] = df[c].fillna(df[c].median())
            else:
                df[c] = df[c].fillna(df[c].mode().iloc[0] if len(df[c].mode()) else "")
        df = df.drop_duplicates()
        info["rows_after"], info["cols_after"] = len(df), len(df.columns)
        return df, info

    def analyze_structure(self, df: pd.DataFrame) -> dict:
        numeric = df.select_dtypes(include=np.number).columns.tolist()
        categorical = df.select_dtypes(exclude=np.number).columns.tolist()
        return {
            "rows": df.shape[0],
            "columns": df.shape[1],
            "numeric_cols": numeric,
            "categorical_cols": categorical,
            "missing_values": df.isnull().sum().to_dict(),
        }

# --- Cell 4: Statistical Engine (summary + trend + outliers) ---
class StatisticalEngine:
    """Summary statistics, trend analysis, outlier detection."""

    def summary_stats(self, df: pd.DataFrame) -> dict:
        return df.describe().to_dict()

    def correlation(self, df: pd.DataFrame) -> pd.DataFrame:
        num = df.select_dtypes(include=np.number)
        return num.corr() if num.shape[1] > 0 else pd.DataFrame()

    def trend_analysis(self, df: pd.DataFrame, metadata: dict) -> dict:
        """Detect time-like column and linear trend on first numeric series."""
        trends = {}
        num_cols = metadata.get("numeric_cols", [])
        if not num_cols:
            return trends
        # Try to find a time/date column
        for c in df.columns:
            if any(k in c.lower() for k in ["date", "time", "year", "month"]):
                try:
                    s = pd.to_numeric(df[c].dropna(), errors="coerce")
                    if s.notna().sum() > 2:
                        slope, intercept, r, p, se = stats.linregress(np.arange(len(s)), s)
                        trends["time_column"] = c
                        trends["slope"] = round(float(slope), 4)
                        trends["r_squared"] = round(r ** 2, 4)
                        break
                except Exception:
                    pass
        # Trend on first numeric column if no time col
        if not trends and len(num_cols) >= 1:
            s = df[num_cols[0]].dropna().reset_index(drop=True)
            if len(s) > 2:
                slope, _, r, _, _ = stats.linregress(np.arange(len(s)), s)
                trends["series"] = num_cols[0]
                trends["slope"] = round(float(slope), 4)
                trends["r_squared"] = round(r ** 2, 4)
        return trends

    def detect_outliers(self, df: pd.DataFrame) -> dict:
        num = df.select_dtypes(include=np.number)
        if num.shape[1] == 0:
            return {"outliers_detected": 0}
        model = IsolationForest(contamination=0.05, random_state=42)
        preds = model.fit_predict(num.fillna(num.median()))
        return {"outliers_detected": int((preds == -1).sum())}

# --- Cell 5: Analysis Planner (agent-decided charts) ---
class AnalysisPlannerAgent:
    """Decides which visualizations to generate from metadata."""

    def plan(self, metadata: dict) -> list[str]:
        plan = []
        if metadata.get("numeric_cols"):
            plan.append("distribution")
        if len(metadata.get("numeric_cols", [])) > 1:
            plan.append("correlation")
        if metadata.get("categorical_cols"):
            plan.append("category_analysis")
        return plan

# --- Cell 6: Visualization Agent (Matplotlib — no Kaleido) ---
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

class VisualizationAgent:
    """Generate chart images; uses Matplotlib so Colab does not need Kaleido."""

    def generate(self, df: pd.DataFrame, plan: list[str]) -> list[str]:
        charts = []
        os.makedirs("charts", exist_ok=True)

        if "distribution" in plan:
            num_cols = df.select_dtypes(include=np.number).columns[:3]
            for col in num_cols:
                fig, ax = plt.subplots(figsize=(6, 4))
                data = df[col].dropna()
                bins = min(50, max(10, len(data.unique())))
                ax.hist(data, bins=bins, edgecolor="black", alpha=0.7)
                ax.set_title(f"Distribution of {col}")
                ax.set_xlabel(col)
                path = f"charts/{col}_hist.png"
                fig.savefig(path, dpi=150, bbox_inches="tight")
                plt.close(fig)
                charts.append(path)

        if "correlation" in plan:
            corr = df.corr(numeric_only=True)
            if corr.shape[0] > 0:
                fig, ax = plt.subplots(figsize=(8, 6))
                sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0, ax=ax, square=True)
                ax.set_title("Correlation matrix")
                path = "charts/correlation.png"
                fig.savefig(path, dpi=150, bbox_inches="tight")
                plt.close(fig)
                charts.append(path)

        if "category_analysis" in plan:
            cat_cols = df.select_dtypes(exclude=np.number).columns
            if len(cat_cols) > 0:
                cat = cat_cols[0]
                counts = df[cat].value_counts().head(20)
                fig, ax = plt.subplots(figsize=(8, 4))
                counts.plot(kind="bar", ax=ax, edgecolor="black", alpha=0.7)
                ax.set_title(f"Count of {cat}")
                ax.set_xlabel(cat)
                plt.xticks(rotation=45, ha="right")
                path = "charts/category.png"
                fig.savefig(path, dpi=150, bbox_inches="tight")
                plt.close(fig)
                charts.append(path)

        return charts

import os
import time
import json
import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest
from scipy import stats
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from tqdm import tqdm
def get_openai_client():
    from openai import OpenAI
    from google.colab import userdata
    api_key_raw = userdata.get("OPENAI_API_KEY")
    if not api_key_raw or not api_key_raw.strip():
        raise ValueError("Set OPENAI_API_KEY in environment or Colab Secrets")
    return OpenAI(api_key=api_key_raw.strip(), http_client=None)

class InsightGeneratorAgent:
    """Generate business insights using LLM."""

    def __init__(self, client=None):
        self.client = client or get_openai_client()

    def generate_insights(self, metadata: dict, stats: dict, outliers: dict, trends: dict) -> str:
        prompt = f"""You are a senior business data analyst. Summarize in clear, actionable bullets.

Dataset: {metadata.get('rows')} rows, {metadata.get('columns')} columns.
Numeric: {metadata.get('numeric_cols', [])}.
Categorical: {metadata.get('categorical_cols', [])}.

Summary statistics (sample): {json.dumps({k: list(v.keys())[:3] for k, v in list(stats.items())[:2]}, default=str)}
Outliers: {outliers}
Trends: {trends}

Provide:
1. Key insights (2–3 bullets)
2. Trends (1–2 bullets)
3. Risks (1–2 bullets)
4. Business recommendations (2–3 bullets)
Keep total under 300 words."""

        try:
            r = self.client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3,
            )
            return r.choices[0].message.content
        except Exception as e:
            return f"[LLM unavailable: {e}]\n\nKey stats: {metadata}. Outliers: {outliers}. Trends: {trends}."

# --- Cell 8: PDF Report Compiler ---
class ReportCompilerAgent:
    """Build human-readable PDF with insights and chart images."""

    def create_pdf(self, metadata: dict, clean_info: dict, insights: str, charts: list[str], timing: float) -> str:
        os.makedirs("output", exist_ok=True)
        path = "output/AI_EDA_Report.pdf"
        doc = SimpleDocTemplate(path, pagesize=A4, topMargin=0.5*inch, bottomMargin=0.5*inch)
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=18, spaceAfter=12)
        story = []

        story.append(Paragraph("AI Data Insights Report — Analyst in a Box", title_style))
        story.append(Paragraph(f"Use Case 5 — AI Hackathon Lucknow Feb 21' 2026", styles["Normal"]))
        story.append(Spacer(1, 16))

        story.append(Paragraph("<b>Dataset</b>", styles["Heading2"]))
        story.append(Paragraph(
            f"Rows: {metadata.get('rows')}, Columns: {metadata.get('columns')}. "
            f"Numeric: {metadata.get('numeric_cols', [])}; Categorical: {metadata.get('categorical_cols', [])}.",
            styles["Normal"]
        ))
        story.append(Spacer(1, 12))

        story.append(Paragraph("<b>Data cleaning</b>", styles["Heading2"]))
        story.append(Paragraph(f"Before: {clean_info.get('rows_before')} rows, {clean_info.get('cols_before')} cols. After: {clean_info.get('rows_after')} rows, {clean_info.get('cols_after')} cols.", styles["Normal"]))
        story.append(Spacer(1, 12))

        story.append(Paragraph("<b>Business insights</b>", styles["Heading2"]))
        for line in insights.strip().split("\n"):
            if line.strip():
                story.append(Paragraph(line.strip().replace("<", "&lt;").replace(">", "&gt;"), styles["Normal"]))
        story.append(Spacer(1, 12))

        story.append(Paragraph("<b>Charts</b>", styles["Heading2"]))
        for chart in charts:
            if os.path.exists(chart):
                story.append(Spacer(1, 12))
                story.append(Image(chart, width=400, height=250))
        story.append(Spacer(1, 12))
        story.append(Paragraph(f"<i>Report generated in {timing:.1f} seconds.</i>", styles["Normal"]))

        doc.build(story)
        print("PDF created:", path)
        return path

# --- Cell 9: Full pipeline ---
def run_pipeline(file_path: str, openai_client=None) -> dict:
    """Run full pipeline: clean → stats → trends → outliers → plan → charts → insights → PDF."""
    start = time.time()
    data_agent = DataUnderstandingAgent()
    stats_engine = StatisticalEngine()
    planner = AnalysisPlannerAgent()
    viz_agent = VisualizationAgent()
    insight_agent = InsightGeneratorAgent(client=openai_client)
    report_agent = ReportCompilerAgent()

    df, clean_info = data_agent.load_data(file_path)
    metadata = data_agent.analyze_structure(df)
    stats = stats_engine.summary_stats(df)
    outliers = stats_engine.detect_outliers(df)
    trends = stats_engine.trend_analysis(df, metadata)
    plan = planner.plan(metadata)
    charts = viz_agent.generate(df, plan)
    insights = insight_agent.generate_insights(metadata, stats, outliers, trends)
    report_path = report_agent.create_pdf(metadata, clean_info, insights, charts, timing=time.time() - start)

    elapsed = time.time() - start
    return {"report": report_path, "charts": charts, "insights": insights, "time_seconds": round(elapsed, 2)}

# --- Cell 10: Colab entrypoint (upload → run → download) ---
def run_in_colab():
    """Use in Google Colab: upload CSV, run pipeline, download PDF."""
    try:
        from google.colab import files
        use_colab = True
    except ImportError:
        use_colab = False

    if use_colab:
        uploaded = files.upload()
        file_name = list(uploaded.keys())[0]
    else:
        file_name = input("Path to CSV file: ").strip()
        if not os.path.exists(file_name):
            raise FileNotFoundError(file_name)

    print("Uploaded:", file_name)
    result = run_pipeline(file_name)
    print("Report:", result["report"])
    print("Time:", result["time_seconds"], "seconds")

    if use_colab:
        files.download(result["report"])
    return result


if __name__ == "__main__":
    run_in_colab()